// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168

#pragma warning disable SA1200 // Using directives should be placed correctly
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Formatters.Neo.BlockchainToolkit.TraceDebug
{
    using System;
    using System.Buffers;
    using System.Collections.Generic;
    using MessagePack;

    public sealed class ITraceRecordFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Neo.BlockchainToolkit.TraceDebug.ITraceRecord>
    {
        private readonly Dictionary<RuntimeTypeHandle, KeyValuePair<int, int>> typeToKeyAndJumpMap;
        private readonly Dictionary<int, int> keyToJumpMap;

        public ITraceRecordFormatter()
        {
            this.typeToKeyAndJumpMap = new Dictionary<RuntimeTypeHandle, KeyValuePair<int, int>>(5, global::MessagePack.Internal.RuntimeTypeHandleEqualityComparer.Default)
            {
                { typeof(global::Neo.BlockchainToolkit.TraceDebug.TracePoint).TypeHandle, new KeyValuePair<int, int>(0, 0) },
                { typeof(global::Neo.BlockchainToolkit.TraceDebug.Notify).TypeHandle, new KeyValuePair<int, int>(1, 1) },
                { typeof(global::Neo.BlockchainToolkit.TraceDebug.Log).TypeHandle, new KeyValuePair<int, int>(2, 2) },
                { typeof(global::Neo.BlockchainToolkit.TraceDebug.Results).TypeHandle, new KeyValuePair<int, int>(3, 3) },
                { typeof(global::Neo.BlockchainToolkit.TraceDebug.Fault).TypeHandle, new KeyValuePair<int, int>(4, 4) },
            };
            this.keyToJumpMap = new Dictionary<int, int>(5)
            {
                { 0, 0 },
                { 1, 1 },
                { 2, 2 },
                { 3, 3 },
                { 4, 4 },
            };
        }

        public void Serialize(ref MessagePackWriter writer, global::Neo.BlockchainToolkit.TraceDebug.ITraceRecord value, global::MessagePack.MessagePackSerializerOptions options)
        {
            KeyValuePair<int, int> keyValuePair;
            if (value != null && this.typeToKeyAndJumpMap.TryGetValue(value.GetType().TypeHandle, out keyValuePair))
            {
                writer.WriteArrayHeader(2);
                writer.WriteInt32(keyValuePair.Key);
                switch (keyValuePair.Value)
                {
                    case 0:
                        options.Resolver.GetFormatterWithVerify<global::Neo.BlockchainToolkit.TraceDebug.TracePoint>().Serialize(ref writer, (global::Neo.BlockchainToolkit.TraceDebug.TracePoint)value, options);
                        break;
                    case 1:
                        options.Resolver.GetFormatterWithVerify<global::Neo.BlockchainToolkit.TraceDebug.Notify>().Serialize(ref writer, (global::Neo.BlockchainToolkit.TraceDebug.Notify)value, options);
                        break;
                    case 2:
                        options.Resolver.GetFormatterWithVerify<global::Neo.BlockchainToolkit.TraceDebug.Log>().Serialize(ref writer, (global::Neo.BlockchainToolkit.TraceDebug.Log)value, options);
                        break;
                    case 3:
                        options.Resolver.GetFormatterWithVerify<global::Neo.BlockchainToolkit.TraceDebug.Results>().Serialize(ref writer, (global::Neo.BlockchainToolkit.TraceDebug.Results)value, options);
                        break;
                    case 4:
                        options.Resolver.GetFormatterWithVerify<global::Neo.BlockchainToolkit.TraceDebug.Fault>().Serialize(ref writer, (global::Neo.BlockchainToolkit.TraceDebug.Fault)value, options);
                        break;
                    default:
                        break;
                }

                return;
            }

            writer.WriteNil();
        }

        public global::Neo.BlockchainToolkit.TraceDebug.ITraceRecord Deserialize(ref MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            if (reader.ReadArrayHeader() != 2)
            {
                throw new InvalidOperationException("Invalid Union data was detected. Type:global::Neo.BlockchainToolkit.TraceDebug.ITraceRecord");
            }

            options.Security.DepthStep(ref reader);
            var key = reader.ReadInt32();

            if (!this.keyToJumpMap.TryGetValue(key, out key))
            {
                key = -1;
            }

            global::Neo.BlockchainToolkit.TraceDebug.ITraceRecord result = null;
            switch (key)
            {
                case 0:
                    result = (global::Neo.BlockchainToolkit.TraceDebug.ITraceRecord)options.Resolver.GetFormatterWithVerify<global::Neo.BlockchainToolkit.TraceDebug.TracePoint>().Deserialize(ref reader, options);
                    break;
                case 1:
                    result = (global::Neo.BlockchainToolkit.TraceDebug.ITraceRecord)options.Resolver.GetFormatterWithVerify<global::Neo.BlockchainToolkit.TraceDebug.Notify>().Deserialize(ref reader, options);
                    break;
                case 2:
                    result = (global::Neo.BlockchainToolkit.TraceDebug.ITraceRecord)options.Resolver.GetFormatterWithVerify<global::Neo.BlockchainToolkit.TraceDebug.Log>().Deserialize(ref reader, options);
                    break;
                case 3:
                    result = (global::Neo.BlockchainToolkit.TraceDebug.ITraceRecord)options.Resolver.GetFormatterWithVerify<global::Neo.BlockchainToolkit.TraceDebug.Results>().Deserialize(ref reader, options);
                    break;
                case 4:
                    result = (global::Neo.BlockchainToolkit.TraceDebug.ITraceRecord)options.Resolver.GetFormatterWithVerify<global::Neo.BlockchainToolkit.TraceDebug.Fault>().Deserialize(ref reader, options);
                    break;
                default:
                    reader.Skip();
                    break;
            }

            reader.Depth--;
            return result;
        }
    }


}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1200 // Using directives should be placed correctly
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name
