name: Upload Code Coverage

on:
  workflow_run:
    workflows: ["On Pull Request"]
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: coverage
          path: ./coverage
      - name: Code Coverage Summary
        uses: 5monkeys/cobertura-action@v13
        with:
          path: test/test.bctklib/TestResults/*/coverage.cobertura.xml
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          minimum_coverage: 0